#ifndef AlgorithmType_hpp
#define AlgorithmType_hpp

enum AlgorithmType
{
    ALGORITHM_SIMPLE_CORNERS,
    ALGORITHM_REFRESH_BORDER,
    ALGORITHM_LAYER_ONE,
    ALGORITHM_REFRESH_SECTIONS,
    ALGORITHM_LAYER_TWO,
    ALGORITHM_REFRESH_SEGMENTS,
    ALGORITHM_REFRESH_SUBSEGMENTS,
    ALGORITHM_REFRESH_FACE,
    ALGORITHM_REFRESH_COMBINATIONS,
    ALGORITHM_COMBINATIONS_SAFE_MOVES,
    ALGORITHM_COMBINATIONS_LEAST_RISKY
};

#endif
