#ifndef AlgorithmType_hpp
#define AlgorithmType_hpp

enum AlgorithmType
{
    UNHANDLED_TYPE,
    FIRST_MOVE,
    SIMPLE_CORNERS,
    REFRESH_BORDER,
    LAYER_ONE,
    REFRESH_SECTIONS,
    LAYER_TWO,
    REFRESH_SEGMENTS,
    REFRESH_SUBSEGMENTS,
    REFRESH_FACE,
    REFRESH_COMBINATIONS,
    COMBINATIONS_SAFE_MOVES,
    COMBINATIONS_LEAST_RISKY,
    GIVE_UP
};

#endif
